apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "otternose.mapper.name" . }}
rules:
  - apiGroups:
      - ''
    resources:
      - 'endpoints'
      - 'pods'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
  - apiGroups:
      - 'apps'
    resources:
      - 'daemonsets'
      - 'replicasets'
      - 'statefulsets'
    verbs:
      - 'get'
      - 'list'
      - 'watch'