apiVersion: v1
kind: Service
metadata:
  name: {{ template "otterize.mapper.name" . }}
spec:
  selector:
    app: {{ template "otterize.mapper.name" . }}
  ports:
    - protocol: TCP
      port: 9090
      name: http
      targetPort: 9090